FROM python:3.10.8-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install debugpy

COPY . .

CMD [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "." ]
